---
- hosts: all
  become: yes
  become_user: root
  gather_facts: false
  tasks:
    - name: Check if connection is possible
      command: ssh  -o PasswordAuthentication=no -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes {{ ansible_user }}@{{ ansible_host }} echo "Worked"
      delegate_to: 127.0.0.1
      ignore_errors: yes
      become: no
      register: result
      changed_when: False
    - name: If no connection, change user_name
      connection: local
      set_fact:
        ansible_user: "{{ ansible_user_first_run }}"
      when: result is failed 
    - name: 'install python'
      raw: test -e /usr/bin/python || (apt -y update && apt -y upgrade && apt install -y python3-minimal python3-zipstream)
      changed_when: False
    - file:
        path: /root/.ssh
        owner: root
        group: root
        state: directory
        mode: 0700
    - file:
        path: /root/.ssh/authorized_keys
        owner: root
        group: root
        state: touch
        modification_time: preserve
        access_time: preserve
        mode: 0600
    - name: Add keys to authorized_keys for root
      blockinfile:
        insertafter: EOF
        path: /root/.ssh/authorized_keys
        block:  "{{ lookup('template', 'ssh.keys') }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      ignore_errors: yes
    - file:
        path: ~{{ ansible_user_first_run }}/.ssh
        owner: "{{ ansible_user_first_run }}"
        group: "{{ ansible_user_first_run }}"
        state: directory
        mode: 0700
    - file:
        path: ~{{ ansible_user_first_run }}/.ssh/authorized_keys
        owner: "{{ ansible_user_first_run }}"
        group: "{{ ansible_user_first_run }}"
        state: touch
        modification_time: preserve
        access_time: preserve
        mode: 0600
    - name: Add keys to authorized_keys for {{ ansible_user_first_run }}
      blockinfile:
        insertafter: EOF
        path: ~{{ ansible_user_first_run }}/.ssh/authorized_keys
        block:  "{{ lookup('template', 'ssh.keys') }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      ignore_errors: yes
