- name: "Debug distribution"
  debug: var=hostvars[inventory_hostname].ansible_distribution
- name: "Debug version"
  debug: var=hostvars[inventory_hostname].ansible_distribution_version
- name: "Debug major version"
  debug: var=hostvars[inventory_hostname].ansible_major_distribution_version
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars
- name: 'Configure system for ansible'
  include: '{{ item }}'
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
